name: Hello world
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        # Multiple shell commands
        run: |
         echo "This is line one"
         echo "This is line two"
